BOARD = zcu106
#UBOOT_CONFIG = zc70x #TODO does it really matter?
UBOOT_CONFIG = zcu106
#BOARD_MODEL = xilinx.com:zc706:part0:1.0
BOARD_MODEL = xilinx.com:zcu106:part0:2.5
#PART = xc7z045ffg900-2
PART = xczu7ev-ffvc1156-2-e

include ../common/Makefrag.zcu106

